export type HighwayStatus = 'operational' | 'under-construction' | 'partially-operational' | 'planned';
export type LaneType = '2-lane' | '4-lane' | '6-lane' | '8-lane' | 'mixed';
export type HighwayType = 'national-highway' | 'expressway';

export type Highway = {
  id: string;
  name: string;
  number: string;
  type: HighwayType;
  origin: string;
  terminus: string;
  states: string[];
  lengthKm: number;
  lanes: LaneType;
  status: HighwayStatus;
  completionPercent: number;
  region: string;
  description: string;
  facts: string[];
};

export const highways: Highway[] = [
  // ─── NATIONAL HIGHWAYS ────────────────────────────────────────────────
  {
    id: 'nh-44',
    name: 'Srinagar-Kanyakumari Highway',
    number: 'NH 44',
    type: 'national-highway',
    origin: 'Srinagar',
    terminus: 'Kanyakumari',
    states: ['Jammu & Kashmir', 'Punjab', 'Haryana', 'Delhi', 'Uttar Pradesh', 'Madhya Pradesh', 'Maharashtra', 'Telangana', 'Andhra Pradesh', 'Karnataka', 'Tamil Nadu'],
    lengthKm: 4112,
    lanes: 'mixed',
    status: 'operational',
    completionPercent: 100,
    region: 'Pan India',
    description: 'NH 44 is the longest national highway in India, running from Srinagar in the north to Kanyakumari at the southern tip. It was formed by merging the old NH 1, NH 2, NH 3, NH 75, NH 26, NH 7, and other stretches under the 2012 renumbering scheme.',
    facts: [
      'At 4,112 km, it is the longest national highway in India.',
      'It passes through 11 states and union territories, connecting the northernmost to the southernmost point of mainland India.',
      'It was previously known by multiple old numbers including NH 1, NH 2, and NH 7 before the 2012 renumbering.',
    ],
  },
  {
    id: 'nh-48',
    name: 'Delhi-Chennai Highway',
    number: 'NH 48',
    type: 'national-highway',
    origin: 'Delhi',
    terminus: 'Chennai',
    states: ['Delhi', 'Haryana', 'Rajasthan', 'Gujarat', 'Maharashtra', 'Karnataka', 'Andhra Pradesh', 'Tamil Nadu'],
    lengthKm: 2807,
    lanes: 'mixed',
    status: 'operational',
    completionPercent: 100,
    region: 'Pan India',
    description: 'NH 48 connects Delhi to Chennai via Rajasthan, Gujarat, Maharashtra, and Karnataka. It is a major freight corridor carrying goods between northern and southern India through western states.',
    facts: [
      'It spans approximately 2,807 km from the national capital to the capital of Tamil Nadu.',
      'The highway passes through major cities including Jaipur, Udaipur, Ahmedabad, Mumbai, Bengaluru, and Chennai.',
      'Sections of this highway form part of the Golden Quadrilateral project.',
    ],
  },
  {
    id: 'nh-27',
    name: 'Porbandar-Silchar Highway (East-West Corridor)',
    number: 'NH 27',
    type: 'national-highway',
    origin: 'Porbandar',
    terminus: 'Silchar',
    states: ['Gujarat', 'Rajasthan', 'Madhya Pradesh', 'Uttar Pradesh', 'Bihar', 'West Bengal', 'Assam'],
    lengthKm: 3507,
    lanes: 'mixed',
    status: 'operational',
    completionPercent: 100,
    region: 'Pan India',
    description: 'NH 27 forms the backbone of the East-West Corridor of India, connecting Porbandar on the western coast of Gujarat to Silchar in Assam. It is one of the most strategically important highways linking western and northeastern India.',
    facts: [
      'It is part of the East-West Corridor under the National Highways Development Project (NHDP).',
      'The highway traverses diverse terrain from the arid regions of Rajasthan to the lush landscapes of Assam.',
      'At 3,507 km, it is the third-longest national highway in India.',
    ],
  },
  {
    id: 'nh-52',
    name: 'Sangrur-Ankola Highway',
    number: 'NH 52',
    type: 'national-highway',
    origin: 'Sangrur',
    terminus: 'Ankola',
    states: ['Punjab', 'Haryana', 'Rajasthan', 'Gujarat', 'Maharashtra', 'Goa', 'Karnataka'],
    lengthKm: 2317,
    lanes: 'mixed',
    status: 'operational',
    completionPercent: 100,
    region: 'Pan India',
    description: 'NH 52 runs from Sangrur in Punjab to Ankola in Karnataka, traversing seven states across northern, western, and southern India. It connects key agricultural and industrial regions of the country.',
    facts: [
      'The highway stretches 2,317 km from the plains of Punjab to the western coast of Karnataka.',
      'It passes through the major cities of Udaipur, Ahmedabad, and Panaji.',
      'The route traverses the Western Ghats section near Goa and Karnataka.',
    ],
  },
  {
    id: 'nh-30',
    name: 'Sitapur-Ibrahimpatnam Highway',
    number: 'NH 30',
    type: 'national-highway',
    origin: 'Sitapur',
    terminus: 'Ibrahimpatnam',
    states: ['Uttar Pradesh', 'Madhya Pradesh', 'Chhattisgarh', 'Odisha', 'Andhra Pradesh', 'Telangana'],
    lengthKm: 1909,
    lanes: 'mixed',
    status: 'operational',
    completionPercent: 100,
    region: 'Central India',
    description: 'NH 30 runs from Sitapur in Uttar Pradesh to Ibrahimpatnam in Telangana, connecting the Indo-Gangetic plains to the Deccan Plateau. It is an important north-south corridor through central India.',
    facts: [
      'The highway is 1,909 km long, connecting northern UP to Telangana.',
      'It passes through several major cities including Allahabad, Raipur, and Hyderabad.',
      'The route traverses through the mineral-rich regions of Chhattisgarh and Odisha.',
    ],
  },
  {
    id: 'nh-53',
    name: 'Hajira-Paradip Highway',
    number: 'NH 53',
    type: 'national-highway',
    origin: 'Hajira',
    terminus: 'Paradip',
    states: ['Gujarat', 'Maharashtra', 'Madhya Pradesh', 'Chhattisgarh', 'Odisha'],
    lengthKm: 1949,
    lanes: 'mixed',
    status: 'operational',
    completionPercent: 100,
    region: 'Central India',
    description: 'NH 53 connects Hajira in Gujarat to the port town of Paradip in Odisha, traversing the central Indian heartland. It links two major port cities on India\'s western and eastern coasts.',
    facts: [
      'The highway connects two major port facilities: Hajira (Gujarat) and Paradip (Odisha).',
      'At 1,949 km, it runs through the mineral-rich central Indian states of Chhattisgarh and Madhya Pradesh.',
      'It serves as a key corridor for freight transportation between India\'s western and eastern coasts.',
    ],
  },
  {
    id: 'nh-66',
    name: 'Mumbai-Kanyakumari Coastal Highway',
    number: 'NH 66',
    type: 'national-highway',
    origin: 'Mumbai',
    terminus: 'Kanyakumari',
    states: ['Maharashtra', 'Goa', 'Karnataka', 'Kerala', 'Tamil Nadu'],
    lengthKm: 1622,
    lanes: 'mixed',
    status: 'operational',
    completionPercent: 100,
    region: 'West India',
    description: 'NH 66 is the famous coastal highway running along India\'s western coast from Mumbai to Kanyakumari. Previously known as NH 17, it is one of the most scenic highways in India, passing through the Konkan coast, Malabar coast, and numerous beach towns.',
    facts: [
      'It is one of the most scenic highways in India, running along the Arabian Sea coastline.',
      'Previously numbered as NH 17, it was renumbered to NH 66 in the 2012 highway renumbering.',
      'The highway passes through Goa, which makes it one of the busiest tourist routes on the western coast.',
    ],
  },
  {
    id: 'nh-19',
    name: 'Delhi-Kolkata Highway (Grand Trunk Road)',
    number: 'NH 19',
    type: 'national-highway',
    origin: 'Delhi',
    terminus: 'Kolkata',
    states: ['Delhi', 'Uttar Pradesh', 'Bihar', 'Jharkhand', 'West Bengal'],
    lengthKm: 1435,
    lanes: 'mixed',
    status: 'operational',
    completionPercent: 100,
    region: 'North India',
    description: 'NH 19 follows the historic Grand Trunk Road from Delhi to Kolkata, one of Asia\'s oldest and longest major roads. The highway is part of the Golden Quadrilateral project and is one of the busiest freight corridors in India.',
    facts: [
      'It follows the alignment of the historic Grand Trunk Road (GT Road), one of the oldest roads in Asia dating back to the Mauryan Empire.',
      'The highway forms the northern arm of the Golden Quadrilateral, connecting Delhi and Kolkata.',
      'Previously known as NH 2, it was renumbered to NH 19 in the 2012 renumbering scheme.',
    ],
  },
  {
    id: 'nh-16',
    name: 'Nellore-Guwahati Highway',
    number: 'NH 16',
    type: 'national-highway',
    origin: 'Nellore',
    terminus: 'Guwahati',
    states: ['Andhra Pradesh', 'Odisha', 'West Bengal', 'Jharkhand', 'Bihar', 'Assam'],
    lengthKm: 2637,
    lanes: 'mixed',
    status: 'operational',
    completionPercent: 100,
    region: 'East India',
    description: 'NH 16 is one of the longest national highways in India, connecting Nellore in Andhra Pradesh to Guwahati in Assam. It runs along the eastern coast for a significant portion and connects major cities like Visakhapatnam, Bhubaneswar, and Kolkata.',
    facts: [
      'At 2,637 km, it connects southeastern India to the northeastern gateway city of Guwahati.',
      'The highway runs along the Bay of Bengal coast through key port cities including Visakhapatnam and Paradip.',
      'Parts of this highway overlap with sections of the Golden Quadrilateral.',
    ],
  },
  {
    id: 'nh-48-blr-mng',
    name: 'Bangalore-Mangalore Highway',
    number: 'NH 48',
    type: 'national-highway',
    origin: 'Bengaluru',
    terminus: 'Mangalore',
    states: ['Karnataka'],
    lengthKm: 353,
    lanes: '4-lane',
    status: 'operational',
    completionPercent: 100,
    region: 'South India',
    description: 'This section of NH 48 connects Bengaluru to the port city of Mangalore via Hassan, passing through the Western Ghats. It is one of the most important highways in Karnataka for trade and commerce.',
    facts: [
      'The highway passes through the scenic Shiradi Ghat section in the Western Ghats.',
      'It connects the IT capital Bengaluru to the major port city of Mangalore (New Mangalore Port).',
      'The Shiradi Ghat section is notorious for landslides during monsoons and is being upgraded to a 4-lane highway.',
    ],
  },
  {
    id: 'nh-2',
    name: 'Dibrugarh-Siaha Highway',
    number: 'NH 2',
    type: 'national-highway',
    origin: 'Dibrugarh',
    terminus: 'Siaha',
    states: ['Assam', 'Nagaland', 'Manipur', 'Mizoram'],
    lengthKm: 1326,
    lanes: '2-lane',
    status: 'operational',
    completionPercent: 100,
    region: 'Northeast India',
    description: 'NH 2 connects Dibrugarh in Assam to Siaha in Mizoram, traversing through the heart of Northeast India. It is a critical lifeline for the northeastern states, passing through some of the most remote and mountainous terrain in India.',
    facts: [
      'The highway passes through four northeastern states: Assam, Nagaland, Manipur, and Mizoram.',
      'At 1,326 km, it is one of the longest highways in the Northeast region.',
      'The route passes through the strategic town of Imphal in Manipur.',
    ],
  },
  {
    id: 'nh-7',
    name: 'Fazilka-Mana Pass Highway',
    number: 'NH 7',
    type: 'national-highway',
    origin: 'Fazilka',
    terminus: 'Mana Pass',
    states: ['Punjab', 'Haryana', 'Uttar Pradesh', 'Uttarakhand'],
    lengthKm: 854,
    lanes: '2-lane',
    status: 'operational',
    completionPercent: 100,
    region: 'North India',
    description: 'NH 7 runs from Fazilka on the India-Pakistan border in Punjab to Mana Pass near the India-China border in Uttarakhand. It is a strategically important border highway connecting two international boundaries.',
    facts: [
      'It connects two international borders: the India-Pakistan border at Fazilka and the India-China border at Mana Pass.',
      'Mana Pass at approximately 5,610 m is one of the highest motorable passes in the world.',
      'The highway passes through the pilgrimage town of Badrinath in Uttarakhand.',
    ],
  },
  {
    id: 'nh-9',
    name: 'Fazilka-Jauljibi Highway',
    number: 'NH 9',
    type: 'national-highway',
    origin: 'Fazilka',
    terminus: 'Jauljibi',
    states: ['Punjab', 'Haryana', 'Uttar Pradesh', 'Uttarakhand'],
    lengthKm: 954,
    lanes: '2-lane',
    status: 'operational',
    completionPercent: 100,
    region: 'North India',
    description: 'NH 9 connects Fazilka in Punjab to Jauljibi in Uttarakhand, running through the northern plains and into the foothills of the Himalayas. It serves as an important east-west link across the upper Gangetic plains.',
    facts: [
      'The highway runs 954 km from the plains of Punjab to the Nepal border area in Uttarakhand.',
      'Jauljibi is located at the confluence of the Gori and Kali rivers near the India-Nepal border.',
      'The route passes through key cities like Chandigarh and several hill stations in Uttarakhand.',
    ],
  },
  {
    id: 'nh-10',
    name: 'Delhi-Fazilka Highway',
    number: 'NH 10',
    type: 'national-highway',
    origin: 'Delhi',
    terminus: 'Fazilka',
    states: ['Delhi', 'Haryana', 'Punjab'],
    lengthKm: 498,
    lanes: '4-lane',
    status: 'operational',
    completionPercent: 100,
    region: 'North India',
    description: 'NH 10 connects Delhi to Fazilka on the India-Pakistan border in Punjab. It passes through the agricultural heartland of Haryana and Punjab, serving as an important trade and defense corridor.',
    facts: [
      'The highway ends at Fazilka, which is a border town near the India-Pakistan international boundary.',
      'It passes through major cities like Hisar and Abohar in the Punjab-Haryana region.',
      'The route is an important corridor for transporting agricultural produce from Punjab and Haryana to Delhi.',
    ],
  },
  {
    id: 'nh-12',
    name: 'Jabalpur-Jaipur Highway',
    number: 'NH 12',
    type: 'national-highway',
    origin: 'Jabalpur',
    terminus: 'Jaipur',
    states: ['Madhya Pradesh', 'Rajasthan'],
    lengthKm: 790,
    lanes: '2-lane',
    status: 'operational',
    completionPercent: 100,
    region: 'Central India',
    description: 'NH 12 connects Jabalpur in Madhya Pradesh to Jaipur in Rajasthan, running through the heart of central India. It passes through historically significant cities like Bhopal and Kota.',
    facts: [
      'The highway connects two major state capitals via a 790 km route.',
      'It passes through Bhopal, the capital of Madhya Pradesh, and the industrial city of Kota in Rajasthan.',
      'The route passes near several wildlife sanctuaries and national parks in central India.',
    ],
  },
  {
    id: 'nh-22',
    name: 'Ambala-Barmer Highway',
    number: 'NH 22',
    type: 'national-highway',
    origin: 'Ambala',
    terminus: 'Barmer',
    states: ['Haryana', 'Rajasthan'],
    lengthKm: 882,
    lanes: '2-lane',
    status: 'operational',
    completionPercent: 100,
    region: 'North India',
    description: 'NH 22 connects Ambala in Haryana to Barmer in western Rajasthan, traversing through the Thar Desert region. It is an important defense corridor connecting the military installations in western Rajasthan.',
    facts: [
      'The highway covers 882 km from Ambala to the desert town of Barmer near the Pakistan border.',
      'It passes through the historic cities of Jaipur and Jodhpur in Rajasthan.',
      'Barmer is a key military and defense area near the India-Pakistan border in the Thar Desert.',
    ],
  },
  {
    id: 'nh-24',
    name: 'Delhi-Lucknow Highway',
    number: 'NH 24',
    type: 'national-highway',
    origin: 'Delhi',
    terminus: 'Lucknow',
    states: ['Delhi', 'Uttar Pradesh'],
    lengthKm: 563,
    lanes: '4-lane',
    status: 'operational',
    completionPercent: 100,
    region: 'North India',
    description: 'NH 24 connects the national capital Delhi to the state capital of Uttar Pradesh, Lucknow. It is one of the busiest highways in northern India, carrying heavy passenger and freight traffic between two of India\'s largest cities.',
    facts: [
      'The highway connects two of India\'s most populated urban centers: Delhi (NCR) and Lucknow.',
      'It passes through the industrial cities of Ghaziabad, Moradabad, and Bareilly.',
      'The road carries some of the heaviest traffic loads of any national highway in India.',
    ],
  },
  {
    id: 'nh-25',
    name: 'Lucknow-Shivpuri Highway',
    number: 'NH 25',
    type: 'national-highway',
    origin: 'Lucknow',
    terminus: 'Shivpuri',
    states: ['Uttar Pradesh', 'Madhya Pradesh'],
    lengthKm: 346,
    lanes: '2-lane',
    status: 'operational',
    completionPercent: 100,
    region: 'Central India',
    description: 'NH 25 links Lucknow in Uttar Pradesh to Shivpuri in Madhya Pradesh. It passes through the historically significant region of Bundelkhand and connects to key cities like Kanpur and Jhansi.',
    facts: [
      'The 346 km highway connects the capital of UP to the Gwalior region of Madhya Pradesh.',
      'It passes through Kanpur, one of India\'s largest industrial cities, and the historic city of Jhansi.',
      'The route passes through the Bundelkhand region, known for its historic forts and palaces.',
    ],
  },
  {
    id: 'nh-28',
    name: 'Barauni-Lucknow Highway',
    number: 'NH 28',
    type: 'national-highway',
    origin: 'Barauni',
    terminus: 'Lucknow',
    states: ['Bihar', 'Uttar Pradesh'],
    lengthKm: 570,
    lanes: '2-lane',
    status: 'operational',
    completionPercent: 100,
    region: 'North India',
    description: 'NH 28 connects Barauni in Bihar to Lucknow in Uttar Pradesh, running through the densely populated Indo-Gangetic plain. It links the industrial town of Barauni (home to a major oil refinery) to the state capital of UP.',
    facts: [
      'Barauni is home to the Indian Oil Corporation\'s Barauni Refinery, one of the oldest refineries in India.',
      'The 570 km highway passes through the major cities of Muzaffarpur, Gorakhpur, and Lucknow.',
      'The route runs through one of the most densely populated regions in the world.',
    ],
  },
  {
    id: 'nh-30-duplicate',
    name: 'Sitapur-Ibrahimpatnam Highway',
    number: 'NH 30',
    type: 'national-highway',
    origin: 'Sitapur',
    terminus: 'Ibrahimpatnam',
    states: ['Uttar Pradesh', 'Madhya Pradesh', 'Chhattisgarh', 'Odisha', 'Andhra Pradesh', 'Telangana'],
    lengthKm: 1909,
    lanes: 'mixed',
    status: 'operational',
    completionPercent: 100,
    region: 'Central India',
    description: 'NH 30 is a major north-south corridor connecting Sitapur in Uttar Pradesh to Ibrahimpatnam near Hyderabad in Telangana. It runs through the mineral-rich belt of central India.',
    facts: [
      'This highway provides a direct north-south corridor through central India spanning nearly 1,909 km.',
      'It passes through important cities including Allahabad (Prayagraj), Raipur, and Hyderabad.',
      'The route passes through the coal and mineral-rich regions of Chhattisgarh.',
    ],
  },
  {
    id: 'nh-32',
    name: 'Jamshedpur-Govindpur Highway',
    number: 'NH 32',
    type: 'national-highway',
    origin: 'Jamshedpur',
    terminus: 'Govindpur',
    states: ['Jharkhand'],
    lengthKm: 179,
    lanes: '2-lane',
    status: 'operational',
    completionPercent: 100,
    region: 'East India',
    description: 'NH 32 connects Jamshedpur, the steel city of India, to Govindpur in Jharkhand. Though relatively short, it serves as a vital link in the industrial corridor of Jharkhand.',
    facts: [
      'Jamshedpur is home to Tata Steel, one of the oldest and largest steel plants in India.',
      'The highway serves the industrial belt of Jharkhand, connecting key mining and manufacturing areas.',
      'It passes through the Dalma Hills, known for the Dalma Wildlife Sanctuary.',
    ],
  },
  {
    id: 'nh-34',
    name: 'Dalkhola-Sagar Island Highway',
    number: 'NH 34',
    type: 'national-highway',
    origin: 'Dalkhola',
    terminus: 'Sagar Island',
    states: ['West Bengal'],
    lengthKm: 443,
    lanes: '2-lane',
    status: 'operational',
    completionPercent: 100,
    region: 'East India',
    description: 'NH 34 runs from Dalkhola in northern West Bengal to Sagar Island at the mouth of the Hooghly River in the Bay of Bengal. It passes through the entire length of West Bengal from north to south.',
    facts: [
      'Sagar Island is a famous pilgrimage site where the annual Gangasagar Mela is held.',
      'The highway traverses the entire state of West Bengal from north to south, covering 443 km.',
      'It passes through Kolkata and crosses several major rivers of the Gangetic delta.',
    ],
  },
  {
    id: 'nh-36',
    name: 'Dhubri-Imphal Highway',
    number: 'NH 36',
    type: 'national-highway',
    origin: 'Dhubri',
    terminus: 'Imphal',
    states: ['Assam', 'Meghalaya', 'Manipur'],
    lengthKm: 720,
    lanes: '2-lane',
    status: 'operational',
    completionPercent: 100,
    region: 'Northeast India',
    description: 'NH 36 connects Dhubri in western Assam to Imphal, the capital of Manipur. It is a crucial lifeline for the northeastern states, passing through challenging mountainous terrain.',
    facts: [
      'The highway is one of the key routes connecting the northeastern capital cities.',
      'The route passes through dense forests and mountainous terrain of the Northeast.',
      'Imphal is historically significant as the site of the Battle of Imphal during World War II.',
    ],
  },
  {
    id: 'nh-37',
    name: 'Goalpara-Dimapur Highway',
    number: 'NH 37',
    type: 'national-highway',
    origin: 'Goalpara',
    terminus: 'Dimapur',
    states: ['Assam', 'Nagaland'],
    lengthKm: 460,
    lanes: '2-lane',
    status: 'operational',
    completionPercent: 100,
    region: 'Northeast India',
    description: 'NH 37 connects Goalpara in Assam to Dimapur, the commercial capital of Nagaland. It runs along the south bank of the Brahmaputra River through some of Assam\'s most important tea-growing regions.',
    facts: [
      'The highway passes through Kaziranga National Park, home to the endangered one-horned Indian rhinoceros.',
      'Dimapur was the ancient capital of the Dimasa Kachari kingdom.',
      'The route runs through the tea estates of upper Assam, one of the world\'s largest tea-producing regions.',
    ],
  },
  {
    id: 'nh-38',
    name: 'Makum-Margherita Highway',
    number: 'NH 38',
    type: 'national-highway',
    origin: 'Makum',
    terminus: 'Margherita',
    states: ['Assam'],
    lengthKm: 54,
    lanes: '2-lane',
    status: 'operational',
    completionPercent: 100,
    region: 'Northeast India',
    description: 'NH 38 is a short but historically significant highway connecting Makum to Margherita in upper Assam. It passes through the coal mining region of northeastern India.',
    facts: [
      'Margherita is named after the Queen of Italy, Margherita of Savoy, by Italian railway engineers.',
      'The area is home to some of the oldest coal mines in India, dating back to the British era.',
      'The highway connects to the famous Stilwell Road (Ledo Road), which was built during World War II to supply China.',
    ],
  },
  {
    id: 'nh-40',
    name: 'Jorabat-Shillong Highway',
    number: 'NH 40',
    type: 'national-highway',
    origin: 'Jorabat',
    terminus: 'Shillong',
    states: ['Assam', 'Meghalaya'],
    lengthKm: 103,
    lanes: '2-lane',
    status: 'operational',
    completionPercent: 100,
    region: 'Northeast India',
    description: 'NH 40 connects Jorabat in Assam to Shillong, the capital of Meghalaya and the "Scotland of the East." It is the primary gateway to Shillong and the Khasi Hills.',
    facts: [
      'Shillong is known as the "Scotland of the East" due to its rolling hills and pleasant climate.',
      'The highway passes through the scenic Khasi Hills with dramatic elevation changes.',
      'Despite being only 103 km, the route is critical as the primary access road to Meghalaya\'s capital.',
    ],
  },
  {
    id: 'nh-47',
    name: 'Salem-Kanyakumari Highway',
    number: 'NH 47',
    type: 'national-highway',
    origin: 'Salem',
    terminus: 'Kanyakumari',
    states: ['Tamil Nadu', 'Kerala'],
    lengthKm: 640,
    lanes: 'mixed',
    status: 'operational',
    completionPercent: 100,
    region: 'South India',
    description: 'NH 47 connects Salem in Tamil Nadu to Kanyakumari at the southernmost tip of the Indian subcontinent. The highway passes through major cities in Kerala including Kochi and Thiruvananthapuram.',
    facts: [
      'The highway connects to Kanyakumari, where the Arabian Sea, Bay of Bengal, and Indian Ocean converge.',
      'It passes through Kochi (Cochin), one of the finest natural harbors in the world.',
      'The route passes through the Palakkad Gap, the only significant break in the Western Ghats.',
    ],
  },
  {
    id: 'nh-56',
    name: 'Lucknow-Varanasi Highway',
    number: 'NH 56',
    type: 'national-highway',
    origin: 'Lucknow',
    terminus: 'Varanasi',
    states: ['Uttar Pradesh'],
    lengthKm: 320,
    lanes: '4-lane',
    status: 'operational',
    completionPercent: 100,
    region: 'North India',
    description: 'NH 56 connects the state capital Lucknow to the holy city of Varanasi in Uttar Pradesh. It is one of the most important intra-state highways in UP, connecting key cultural and political centers.',
    facts: [
      'Varanasi is one of the oldest continuously inhabited cities in the world, dating back over 3,000 years.',
      'The highway connects the political capital of UP (Lucknow) to its cultural and spiritual capital (Varanasi).',
      'The route passes through Sultanpur, Jaunpur, and other historically significant cities of the Gangetic plain.',
    ],
  },
  {
    id: 'nh-58',
    name: 'Delhi-Mana Pass Highway',
    number: 'NH 58',
    type: 'national-highway',
    origin: 'Delhi',
    terminus: 'Mana Pass',
    states: ['Delhi', 'Uttar Pradesh', 'Uttarakhand'],
    lengthKm: 538,
    lanes: 'mixed',
    status: 'operational',
    completionPercent: 100,
    region: 'North India',
    description: 'NH 58 connects Delhi to Mana Pass near the Indo-China border in Uttarakhand. The highway climbs from the plains of Delhi to one of the highest motorable passes in India, passing through the sacred pilgrimage town of Badrinath.',
    facts: [
      'Mana Pass at over 5,600 m elevation is one of the highest motorable passes in the world.',
      'The highway passes through Rishikesh and Badrinath, two of India\'s most important pilgrimage destinations.',
      'The last inhabited village on this route is Mana village, often called the "last village of India."',
    ],
  },
  {
    id: 'nh-65',
    name: 'Pune-Machilipatnam Highway',
    number: 'NH 65',
    type: 'national-highway',
    origin: 'Pune',
    terminus: 'Machilipatnam',
    states: ['Maharashtra', 'Karnataka', 'Telangana', 'Andhra Pradesh'],
    lengthKm: 841,
    lanes: 'mixed',
    status: 'operational',
    completionPercent: 100,
    region: 'South India',
    description: 'NH 65 connects Pune in Maharashtra to the port town of Machilipatnam in Andhra Pradesh. It passes through Hyderabad and is a major east-west corridor in the Deccan Plateau region.',
    facts: [
      'The highway connects Pune, the cultural capital of Maharashtra, to the historic port of Machilipatnam.',
      'It passes through Hyderabad, the capital of Telangana and a major IT hub.',
      'Machilipatnam was one of the earliest European trading posts in India, established by the Dutch and British.',
    ],
  },

  // ─── EXPRESSWAYS ──────────────────────────────────────────────────────
  {
    id: 'mumbai-pune-expressway',
    name: 'Mumbai-Pune Expressway',
    number: 'Expressway',
    type: 'expressway',
    origin: 'Mumbai',
    terminus: 'Pune',
    states: ['Maharashtra'],
    lengthKm: 94.5,
    lanes: '6-lane',
    status: 'operational',
    completionPercent: 100,
    region: 'West India',
    description: 'The Mumbai-Pune Expressway was India\'s first expressway, opened in 2002. It connects India\'s financial capital Mumbai to the cultural capital of Maharashtra, Pune, reducing travel time from 4 hours to about 2 hours.',
    facts: [
      'It was India\'s first six-lane expressway, inaugurated on 1 April 2002.',
      'The expressway has five tunnels, with the longest being 1.8 km through the Sahyadri mountain range.',
      'It handles over 60,000 vehicles daily, making it one of the busiest expressways in India.',
    ],
  },
  {
    id: 'delhi-meerut-expressway',
    name: 'Delhi-Meerut Expressway',
    number: 'Expressway',
    type: 'expressway',
    origin: 'Delhi',
    terminus: 'Meerut',
    states: ['Delhi', 'Uttar Pradesh'],
    lengthKm: 96,
    lanes: '8-lane',
    status: 'operational',
    completionPercent: 100,
    region: 'North India',
    description: 'The Delhi-Meerut Expressway is a 14-lane (expandable) controlled-access expressway connecting Delhi to Meerut. It is one of the widest expressways in India and significantly reduces travel time between the two cities to under 45 minutes.',
    facts: [
      'With 14 lanes (expandable), it is one of the widest expressways in India.',
      'The expressway reduces the travel time between Delhi and Meerut from 2.5 hours to just 45 minutes.',
      'It was built at an estimated cost of over Rs 8,346 crore.',
    ],
  },
  {
    id: 'agra-lucknow-expressway',
    name: 'Agra-Lucknow Expressway',
    number: 'Expressway',
    type: 'expressway',
    origin: 'Agra',
    terminus: 'Lucknow',
    states: ['Uttar Pradesh'],
    lengthKm: 302,
    lanes: '6-lane',
    status: 'operational',
    completionPercent: 100,
    region: 'North India',
    description: 'The Agra-Lucknow Expressway is a 6-lane (expandable to 8) controlled-access expressway in Uttar Pradesh. Inaugurated in 2016, it connects the Taj city of Agra to the state capital Lucknow.',
    facts: [
      'It was inaugurated by Chief Minister Akhilesh Yadav on 21 November 2016.',
      'The expressway was built in a record time of 22 months at a cost of approximately Rs 14,000 crore.',
      'It connects five districts of UP and has an airstrip for emergency landing near Unnao.',
    ],
  },
  {
    id: 'yamuna-expressway',
    name: 'Yamuna Expressway',
    number: 'Expressway',
    type: 'expressway',
    origin: 'Greater Noida',
    terminus: 'Agra',
    states: ['Uttar Pradesh'],
    lengthKm: 165,
    lanes: '6-lane',
    status: 'operational',
    completionPercent: 100,
    region: 'North India',
    description: 'The Yamuna Expressway (officially Taj Expressway) is a 6-lane controlled-access expressway connecting Greater Noida to Agra. It is one of the longest expressways in India and provides quick access to the Taj Mahal from Delhi NCR.',
    facts: [
      'It was the longest expressway in India when opened in August 2012.',
      'The expressway connects Noida to Agra, reducing the Delhi-Agra travel time to about 2 hours.',
      'The Buddh International Circuit (Formula 1 track) and the upcoming Jewar International Airport are located along this expressway.',
    ],
  },
  {
    id: 'eastern-peripheral-expressway',
    name: 'Eastern Peripheral Expressway',
    number: 'Expressway',
    type: 'expressway',
    origin: 'Kundli',
    terminus: 'Palwal',
    states: ['Haryana', 'Uttar Pradesh'],
    lengthKm: 135,
    lanes: '6-lane',
    status: 'operational',
    completionPercent: 100,
    region: 'North India',
    description: 'The Eastern Peripheral Expressway (also known as Kundli-Ghaziabad-Palwal Expressway) is a ring road bypass around Delhi to divert traffic that does not have Delhi as its destination. It was inaugurated by PM Modi in 2018.',
    facts: [
      'It was the first expressway in India to be inaugurated by PM Narendra Modi in May 2018.',
      'The expressway was built as a "green expressway" powered by solar energy.',
      'It was constructed in a record 500 days and has helped reduce Delhi\'s vehicular pollution significantly.',
    ],
  },
  {
    id: 'western-peripheral-expressway',
    name: 'Western Peripheral Expressway',
    number: 'Expressway',
    type: 'expressway',
    origin: 'Kundli',
    terminus: 'Palwal',
    states: ['Haryana'],
    lengthKm: 135.6,
    lanes: '6-lane',
    status: 'operational',
    completionPercent: 100,
    region: 'North India',
    description: 'The Western Peripheral Expressway (also known as Kundli-Manesar-Palwal Expressway or KMP Expressway) runs on the western side of Delhi. Together with the Eastern Peripheral Expressway, it forms a complete ring around the capital.',
    facts: [
      'Combined with the Eastern Peripheral Expressway, it forms a 270 km ring around Delhi.',
      'The expressway took over a decade to complete due to land acquisition issues.',
      'It passes through the industrial hub of Manesar, home to many automobile manufacturing plants.',
    ],
  },
  {
    id: 'mumbai-nagpur-expressway',
    name: 'Samruddhi Mahamarg (Mumbai-Nagpur Expressway)',
    number: 'Expressway',
    type: 'expressway',
    origin: 'Mumbai',
    terminus: 'Nagpur',
    states: ['Maharashtra'],
    lengthKm: 701,
    lanes: '8-lane',
    status: 'partially-operational',
    completionPercent: 75,
    region: 'West India',
    description: 'The Samruddhi Mahamarg (Hindu Hrudaysamrat Balasaheb Thackeray Maharashtra Samruddhi Mahamarg) is a mega expressway connecting Mumbai to Nagpur. The first phase was opened in 2022, and the full route aims to cut travel time from 16 hours to 8 hours.',
    facts: [
      'At 701 km, it is one of the longest expressways in India when fully operational.',
      'The expressway will pass through 10 districts of Maharashtra and boost connectivity to the Vidarbha region.',
      'It is designed to have an airstrip for emergency landings and will connect to the new Navi Mumbai International Airport.',
    ],
  },
  {
    id: 'delhi-mumbai-expressway',
    name: 'Delhi-Mumbai Expressway',
    number: 'Expressway',
    type: 'expressway',
    origin: 'Delhi',
    terminus: 'Mumbai',
    states: ['Delhi', 'Haryana', 'Rajasthan', 'Madhya Pradesh', 'Gujarat', 'Maharashtra'],
    lengthKm: 1386,
    lanes: '8-lane',
    status: 'under-construction',
    completionPercent: 65,
    region: 'Pan India',
    description: 'The Delhi-Mumbai Expressway is India\'s longest expressway under construction, connecting Delhi to Mumbai via an 8-lane (expandable to 12) controlled-access highway. It is expected to reduce travel time between the two cities from 24 hours to about 12 hours.',
    facts: [
      'At 1,386 km, it will be the longest expressway in India when completed.',
      'The expressway will pass through six states and is being built at a cost of approximately Rs 98,000 crore.',
      'It will feature animal overpasses and underpasses, making it India\'s first wildlife-friendly expressway.',
    ],
  },
  {
    id: 'bengaluru-mysuru-expressway',
    name: 'Bengaluru-Mysuru Expressway',
    number: 'Expressway',
    type: 'expressway',
    origin: 'Bengaluru',
    terminus: 'Mysuru',
    states: ['Karnataka'],
    lengthKm: 117,
    lanes: '6-lane',
    status: 'operational',
    completionPercent: 100,
    region: 'South India',
    description: 'The Bengaluru-Mysuru Expressway is a 6-lane (expandable to 10) expressway connecting the IT capital Bengaluru to the heritage city of Mysuru. Inaugurated in 2023, it reduces travel time to about 90 minutes.',
    facts: [
      'The expressway was inaugurated by PM Modi in March 2023.',
      'It reduces travel time between Bengaluru and Mysuru from 3 hours to about 90 minutes.',
      'The route passes through Mandya district, known as the sugar bowl of Karnataka.',
    ],
  },
  {
    id: 'dwarka-expressway',
    name: 'Dwarka Expressway',
    number: 'Expressway',
    type: 'expressway',
    origin: 'Dwarka (Delhi)',
    terminus: 'Gurugram (NH-48 Junction)',
    states: ['Delhi', 'Haryana'],
    lengthKm: 29,
    lanes: '8-lane',
    status: 'operational',
    completionPercent: 100,
    region: 'North India',
    description: 'The Dwarka Expressway (Northern Peripheral Road) is an 8-lane expressway connecting Dwarka in Delhi to NH-48 in Gurugram. Inaugurated in 2024, it is designed to decongest the Delhi-Gurugram corridor.',
    facts: [
      'The expressway features India\'s first elevated urban expressway section of 3.6 km.',
      'It was inaugurated by PM Modi in March 2024 and has an 8-lane access-controlled design.',
      'The Dwarka Expressway is expected to boost real estate development in the Dwarka and New Gurugram areas.',
    ],
  },
  {
    id: 'bundelkhand-expressway',
    name: 'Bundelkhand Expressway',
    number: 'Expressway',
    type: 'expressway',
    origin: 'Chitrakoot',
    terminus: 'Etawah',
    states: ['Uttar Pradesh'],
    lengthKm: 296,
    lanes: '4-lane',
    status: 'operational',
    completionPercent: 100,
    region: 'Central India',
    description: 'The Bundelkhand Expressway is a 4-lane (expandable to 6) expressway connecting the backward Bundelkhand region to Etawah and onwards to Delhi via the Agra-Lucknow Expressway. Inaugurated in 2022, it aims to boost development in the underdeveloped region.',
    facts: [
      'The expressway was inaugurated by PM Narendra Modi on 16 July 2022.',
      'It passes through seven districts of Uttar Pradesh including Chitrakoot, Banda, and Hamirpur.',
      'It connects to the Agra-Lucknow Expressway and Yamuna Expressway, creating a network across UP.',
    ],
  },
  {
    id: 'gorakhpur-link-expressway',
    name: 'Gorakhpur Link Expressway',
    number: 'Expressway',
    type: 'expressway',
    origin: 'Gorakhpur',
    terminus: 'Azamgarh (Purvanchal Expressway Junction)',
    states: ['Uttar Pradesh'],
    lengthKm: 91,
    lanes: '4-lane',
    status: 'operational',
    completionPercent: 100,
    region: 'North India',
    description: 'The Gorakhpur Link Expressway connects Gorakhpur to the Purvanchal Expressway near Azamgarh. It provides the city of Gorakhpur with access to the wider expressway network of Uttar Pradesh.',
    facts: [
      'The expressway connects Gorakhpur to the Purvanchal Expressway, reducing travel time to Lucknow significantly.',
      'It was inaugurated by PM Modi and UP CM Yogi Adityanath.',
      'Gorakhpur is the constituency of UP Chief Minister Yogi Adityanath and a major religious-tourism center.',
    ],
  },
  {
    id: 'purvanchal-expressway',
    name: 'Purvanchal Expressway',
    number: 'Expressway',
    type: 'expressway',
    origin: 'Lucknow',
    terminus: 'Ghazipur',
    states: ['Uttar Pradesh'],
    lengthKm: 341,
    lanes: '6-lane',
    status: 'operational',
    completionPercent: 100,
    region: 'North India',
    description: 'The Purvanchal Expressway is a 6-lane (expandable to 8) expressway connecting Lucknow to Ghazipur in eastern UP. Inaugurated in 2021, it was opened by PM Modi who landed an IAF aircraft on the expressway\'s airstrip during the inauguration.',
    facts: [
      'PM Modi landed on the expressway in an IAF C-130J aircraft during its inauguration in November 2021.',
      'The expressway has a 3.2 km long airstrip near Sultanpur for emergency landing of fighter jets.',
      'It connects nine districts of eastern Uttar Pradesh and has significantly reduced travel time to the state capital.',
    ],
  },
  {
    id: 'ganga-expressway',
    name: 'Ganga Expressway',
    number: 'Expressway',
    type: 'expressway',
    origin: 'Meerut',
    terminus: 'Prayagraj',
    states: ['Uttar Pradesh'],
    lengthKm: 594,
    lanes: '6-lane',
    status: 'under-construction',
    completionPercent: 40,
    region: 'North India',
    description: 'The Ganga Expressway is a 594 km, 6-lane (expandable to 8) expressway being built along the Ganga river in Uttar Pradesh. When completed, it will be the longest expressway in UP, connecting Meerut to Prayagraj.',
    facts: [
      'At 594 km, it will be the longest expressway entirely within Uttar Pradesh.',
      'The foundation stone was laid by PM Modi in December 2021.',
      'The expressway runs roughly parallel to the Ganga river and will connect 12 districts of UP.',
    ],
  },
  {
    id: 'chennai-bengaluru-expressway',
    name: 'Chennai-Bengaluru Expressway',
    number: 'Expressway',
    type: 'expressway',
    origin: 'Chennai',
    terminus: 'Bengaluru',
    states: ['Tamil Nadu', 'Andhra Pradesh', 'Karnataka'],
    lengthKm: 262,
    lanes: '6-lane',
    status: 'under-construction',
    completionPercent: 45,
    region: 'South India',
    description: 'The Chennai-Bengaluru Expressway is a 6-lane (expandable to 8) access-controlled expressway connecting India\'s two major southern IT hubs. It will reduce travel time between Chennai and Bengaluru from 5-6 hours to about 2 hours.',
    facts: [
      'The expressway will reduce travel time between Chennai and Bengaluru from 5-6 hours to approximately 2 hours.',
      'It passes through Andhra Pradesh, connecting all three southern states.',
      'The project is estimated to cost approximately Rs 17,000 crore.',
    ],
  },
  {
    id: 'ahmedabad-dholera-expressway',
    name: 'Ahmedabad-Dholera Expressway',
    number: 'Expressway',
    type: 'expressway',
    origin: 'Ahmedabad',
    terminus: 'Dholera',
    states: ['Gujarat'],
    lengthKm: 109,
    lanes: '6-lane',
    status: 'operational',
    completionPercent: 100,
    region: 'West India',
    description: 'The Ahmedabad-Dholera Expressway connects Ahmedabad to the upcoming Dholera Special Investment Region (SIR). It provides access to India\'s first greenfield smart city being developed at Dholera.',
    facts: [
      'Dholera SIR is being developed as India\'s first greenfield industrial smart city.',
      'The expressway connects to the upcoming Dholera International Airport.',
      'Dholera SIR is planned to be twice the size of Delhi and is a key project under the Delhi-Mumbai Industrial Corridor.',
    ],
  },
  {
    id: 'raipur-visakhapatnam-expressway',
    name: 'Raipur-Visakhapatnam Expressway',
    number: 'Expressway',
    type: 'expressway',
    origin: 'Raipur',
    terminus: 'Visakhapatnam',
    states: ['Chhattisgarh', 'Odisha', 'Andhra Pradesh'],
    lengthKm: 464,
    lanes: '4-lane',
    status: 'planned',
    completionPercent: 5,
    region: 'East India',
    description: 'The Raipur-Visakhapatnam Expressway is a planned 464 km greenfield expressway that will connect the capital of Chhattisgarh to the port city of Visakhapatnam. It aims to provide a direct corridor from central India to the eastern coast.',
    facts: [
      'The expressway will provide a direct route from the mineral-rich Chhattisgarh to the port of Visakhapatnam.',
      'It is expected to significantly reduce logistics costs for the mining and steel industries in the region.',
      'The planned route passes through the dense forests and tribal areas of Odisha and Andhra Pradesh.',
    ],
  },
  {
    id: 'amritsar-jamnagar-expressway',
    name: 'Amritsar-Jamnagar Expressway',
    number: 'Expressway',
    type: 'expressway',
    origin: 'Amritsar',
    terminus: 'Jamnagar',
    states: ['Punjab', 'Haryana', 'Rajasthan', 'Gujarat'],
    lengthKm: 1257,
    lanes: '6-lane',
    status: 'planned',
    completionPercent: 5,
    region: 'North India',
    description: 'The Amritsar-Jamnagar Expressway is a planned 1,257 km expressway that will connect the holy city of Amritsar in Punjab to the port city of Jamnagar in Gujarat. It will be one of the longest expressways in India when completed.',
    facts: [
      'At 1,257 km, it will be among the longest expressways in India.',
      'The expressway will pass through four states: Punjab, Haryana, Rajasthan, and Gujarat.',
      'It will connect the Golden Temple city of Amritsar to the oil refinery hub of Jamnagar (home to the world\'s largest refinery).',
    ],
  },
  {
    id: 'hyderabad-bengaluru-expressway',
    name: 'Hyderabad-Bengaluru Expressway',
    number: 'Expressway',
    type: 'expressway',
    origin: 'Hyderabad',
    terminus: 'Bengaluru',
    states: ['Telangana', 'Andhra Pradesh', 'Karnataka'],
    lengthKm: 186,
    lanes: '6-lane',
    status: 'under-construction',
    completionPercent: 30,
    region: 'South India',
    description: 'The Hyderabad-Bengaluru Expressway is a 6-lane greenfield expressway being built to connect two of India\'s biggest IT hubs. It will reduce the travel time between Hyderabad and Bengaluru from 8 hours to about 3-4 hours.',
    facts: [
      'The expressway will connect India\'s two largest IT corridors: Hyderabad and Bengaluru.',
      'It will reduce travel time from approximately 8 hours to 3-4 hours between the two cities.',
      'The expressway is part of the Bharatmala Pariyojana, India\'s ambitious highway development program.',
    ],
  },
];

// ─── HELPER FUNCTIONS ─────────────────────────────────────────────────

export function getHighwayById(id: string): Highway | undefined {
  return highways.find((h) => h.id === id);
}

export function getHighwaysByState(state: string): Highway[] {
  return highways.filter((h) => h.states.includes(state));
}

export function getHighwaysByStatus(status: HighwayStatus): Highway[] {
  return highways.filter((h) => h.status === status);
}

export function getHighwaysByType(type: HighwayType): Highway[] {
  return highways.filter((h) => h.type === type);
}

export function getAllStates(): string[] {
  const states = new Set<string>();
  highways.forEach((h) => h.states.forEach((s) => states.add(s)));
  return Array.from(states).sort();
}

export function getStats() {
  const totalKm = highways.reduce((sum, h) => sum + h.lengthKm, 0);
  const operational = highways.filter((h) => h.status === 'operational').length;
  const underConstruction = highways.filter((h) => h.status === 'under-construction').length;
  const nhs = highways.filter((h) => h.type === 'national-highway').length;
  const expressways = highways.filter((h) => h.type === 'expressway').length;
  const states = getAllStates().length;
  return { totalKm, operational, underConstruction, nhs, expressways, states, total: highways.length };
}
